= Fantastic bits - jeudi 5 décembre 2024

Un export pdf des actualités est disponible dans ce repo : link:2024.12.05-fantastic-bits-quoi-de-noeuf.pdf[2024.12.05-fantastic-bits-quoi-de-noeuf.pdf] (source : link:2024.12.05-fantastic-bits-quoi-de-noeuf.adoc[2024.12.05-fantastic-bits-quoi-de-noeuf.adoc]).

Repos et présentations des personnes intervenantes :

* **Michel Caradec** : Python benchmarking & profiling. Supports sur https://gitlab.com/reech-oss/meetup/meetup-python-rennes-profiling.

== Voir les diaporamas

La présentation a été écrite pour être visualisée à travers l'extension https://marketplace.visualstudio.com/items?itemName=flobilosaurus.vscode-asciidoc-slides[flobilosaurus.vscode-asciidoc-slides] pour Codium / vsCode.

. affichez la palette de commandes avec `ctrl shift p`
. utilisez la commande `Asciidoc Slides: Open Slides in Browser`
. appuyer sur `s` pour lancer le presenter mode

Documentation de la https://docs.asciidoctor.org/reveal.js-converter/latest/converter/features/[syntaxe asciidoc pour les présentations].

Pour générer un pdf :

. utilisez la commande `Asciidoc Slides: Export document as PDF` (ne fonctionne pas toujours)

ou :

. ouvrir la présentation dans le navigateur chromium / chrome
. rajouter `?print-pdf` à la fin de l'URL
. lancer l'impression en pdf avec `ctrl p` ou `cmd p`

