name: Python CI

on: push

env:
  MIN_CODE_COVERAGE_PERCENT: 97

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Installation de poetry
        uses: abatilo/actions-poetry@v2

      - name: Met en cache l'environnement virtuel
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Installation des dépendances du projet
        run: poetry install --without lint

      - name: Lancement des tests automatisés (avec couverture de code)
        run: >
          poetry run pytest -v --cov=math_cli --cov-branch
          --cov-report term-missing
          --cov-fail-under $MIN_CODE_COVERAGE_PERCENT
