[package_management]
manager = "pip"

[server]
browser = "default"
follow_symlink = false

[runtime]
watcher_on_save = "lazy"
auto_reload = "off"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
on_cell_change = "autorun"
default_auto_download = []
auto_instantiate = true
reactive_tests = true
default_sql_output = "auto"

[completion]
copilot = false
activate_on_typing = true

[diagnostics]

[mcp]
presets = []

[mcp.mcpServers]

[display]
default_table_max_columns = 50
dataframes = "rich"
code_editor_font_size = 14
default_table_page_size = 10
reference_highlighting = false
cell_output = "below"
default_width = "medium"
theme = "light"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[formatting]
line_length = 120

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_pylint = false
enable_mypy = true
enable_ruff = true
enable_pydocstyle = false
enable_pyflakes = false
enabled = true
enable_flake8 = false

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.models]
custom_models = []
displayed_models = []

[snippets]
include_default_snippets = true
custom_paths = []

[experimental]
