[server]
follow_symlink = false
browser = "default"

[experimental]

[completion]
copilot = false
activate_on_typing = true

[display]
dataframes = "rich"
theme = "light"
cell_output = "below"
locale = "fr-FR"
code_editor_font_size = 14
reference_highlighting = false
default_table_page_size = 10
default_table_max_columns = 50
default_width = "full"

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[snippets]
custom_paths = []
include_default_snippets = true

[package_management]
manager = "pip"

[mcp]
presets = []

[mcp.mcpServers]

[runtime]
auto_reload = "off"
reactive_tests = true
default_sql_output = "auto"
default_auto_download = []
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
watcher_on_save = "lazy"
auto_instantiate = true
on_cell_change = "autorun"

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[ai]
inline_tooltip = false
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[diagnostics]

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_ruff = true
enable_pydocstyle = false
enabled = true
enable_pyflakes = false
enable_flake8 = false
enable_mypy = true
enable_pylint = false

[formatting]
line_length = 120
